[package]
name = "chat"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.19"
tui = { version = "0.14.0", features = ["crossterm"], default-features = false }
unicode-width = "0.1"
socket2 = "0.4.0"
